env:
  es2021: true
  mocha: true
  node: true
extends: standard
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  space-before-function-paren:
    - 'error'
    - anonymous: always
      named: never
      asyncArrow: always
